version: '3.8'

services:
  db:
    image: postgres:14
    container_name: education-platform-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - education-network

networks:
  education-network:
    driver: bridge

volumes:
  db-data:
