version: '3.8'

services:
  db:
    image: postgres:14
    container_name: education-platform-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - education-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: education-platform-bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - education-network

networks:
  education-network:
    driver: bridge

volumes:
  db-data:
