version: '3.8'

services:
  db:
    image: postgres:14
    container_name: education-platform-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: education_platform
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
    networks:
      - education-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: education-platform-bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_USER=postgres
      - DB_PASSWORD=your_secure_password
      - DB_NAME=education_platform
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - education-network

networks:
  education-network:
    driver: bridge

volumes:
  db-data:
