# Используем официальный образ PostgreSQL
FROM postgres:14

# Устанавливаем переменные окружения для базы данных
ENV POSTGRES_USER=your_db_user
ENV POSTGRES_PASSWORD=your_db_password
ENV POSTGRES_DB=education_platform

# Копируем файлы миграций в контейнер
COPY migrate.sql /docker-entrypoint-initdb.d/
